version: 2
jobs:
  build:
    docker:
      - image: nimlang/nim
      - image: mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: "httpauth_test"
          MYSQL_ROOT_PASSWORD: ''
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test_test
      # SQLite
      # MySQL
      # PostgreSQL
      # Etcd
      # Redis
      # MongoDB
    steps:
      - run: echo 'export PATH=~/.nimble/bin:$PATH' >> $BASH_ENV
      - checkout
      # Reuse cached Nim compiler
      - restore_cache:
          key: cache-0002
      - run:
          command: |
            apt-get update
            apt-get install -y --no-install-recommends make libmysqlclient-dev libmysqlclient20 libpq5 libsodium23
            nimble install libsodium -y
            nimble install etcd_client -y
      - save_cache:
          key: cache-0002
          paths:
            - ~/.nimble
            - ~/.choosenim
      - run:
          command: make circleci
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
