name: CI
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
        cpu: [amd64]
    name: '${{ matrix.os }} (${{ matrix.cpu }})'
    runs-on: ${{ matrix.os }}

    # Implemented based on:
    # https://help.github.com/en/actions/configuring-and-managing-workflows/creating-postgresql-service-containers
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      - image: mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: "httpauth_test"
          MYSQL_ROOT_PASSWORD: ''
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test_test
      - image: circleci/mongo:latest
      - image: bitnami/etcd:latest
        environment:
          ALLOW_NONE_AUTHENTICATION=yes
      - image: bitnami/redis:latest
        environment:
          - ALLOW_EMPTY_PASSWORD=yes

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Install dependencies (Linux amd64)'
        if: runner.os == 'Linux' && matrix.cpu == 'amd64'
        run: |
          sudo apt-fast update -qq
          DEBIAN_FRONTEND='noninteractive' \
            sudo apt-fast install --no-install-recommends -y \
            make libmysqlclient-dev libmysqlclient21 mysql-client libpq5 libsodium23
          nimble install libsodium -y
          nimble install etcd_client -y

      - name: 'Install dependencies (macOS)'
        if: runner.os == 'macOS'
        run: brew install make

      - name: 'Install dependencies (Windows)'
        if: runner.os == 'Windows'
        shell: bash
        run: |
          true

      - name: 'Install dependencies (Nim)'
          # MongoDB deps
          apt-get install -y mongodb-clients
          nimble install -y scram@#head
          nimble install -y sha1@#head
          nimble install -y hmac@#head
          nimble install -y nimongo@#head
          # Redis
          nimble install -y redis@#head

      - name: 'Add build binaries to PATH'
        shell: bash
        run: echo "::add-path::${{ github.workspace }}/bin"

      - run:
          command: make circleci
